// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Input: typeof import('./src/components/Input.vue')['default']
    IonInput: typeof import('@ionic/vue')['IonInput']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonLabel: typeof import('@ionic/vue')['IonLabel']
    IonList: typeof import('@ionic/vue')['IonList']
    IonNote: typeof import('@ionic/vue')['IonNote']
    IonRadio: typeof import('@ionic/vue')['IonRadio']
    IonRadioGroup: typeof import('@ionic/vue')['IonRadioGroup']
    IonSelect: typeof import('@ionic/vue')['IonSelect']
    IonSelectOption: typeof import('@ionic/vue')['IonSelectOption']
    IonTextarea: typeof import('@ionic/vue')['IonTextarea']
    RadioGroup: typeof import('./src/components/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select.vue')['default']
    Textarea: typeof import('./src/components/Textarea.vue')['default']
  }
}
